[2025-08-14T18:20:54.848+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-14T18:20:54.926+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: orders_pipeline.create_external_raw_orders manual__2025-08-14T17:56:41+00:00 [queued]>
[2025-08-14T18:20:54.959+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: orders_pipeline.create_external_raw_orders manual__2025-08-14T17:56:41+00:00 [queued]>
[2025-08-14T18:20:54.960+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-14T18:20:54.998+0000] {taskinstance.py:2330} INFO - Executing <Task(AthenaOperator): create_external_raw_orders> on 2025-08-14 17:56:41+00:00
[2025-08-14T18:20:55.011+0000] {standard_task_runner.py:64} INFO - Started process 151 to run task
[2025-08-14T18:20:55.017+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'orders_pipeline', 'create_external_raw_orders', 'manual__2025-08-14T17:56:41+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/orders_pipeline.py', '--cfg-path', '/tmp/tmpc_zp395t']
[2025-08-14T18:20:55.020+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask create_external_raw_orders
[2025-08-14T18:20:55.139+0000] {task_command.py:426} INFO - Running <TaskInstance: orders_pipeline.create_external_raw_orders manual__2025-08-14T17:56:41+00:00 [running]> on host 25a9e79e188f
[2025-08-14T18:20:55.400+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-eng' AIRFLOW_CTX_DAG_ID='orders_pipeline' AIRFLOW_CTX_TASK_ID='create_external_raw_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T17:56:41+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-14T17:56:41+00:00'
[2025-08-14T18:20:55.401+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-14T18:20:55.428+0000] {athena.py:132} INFO - Running Query with params:
	QueryString: 
		
		CREATE EXTERNAL TABLE IF NOT EXISTS analytics.raw_orders (
		  order_id   int,
		  order_date date,
		  customer   string,
		  amount     double
		)
		ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
		WITH SERDEPROPERTIES (
		  'serialization.format' = ',',
		  'field.delim'          = ','
		)
		STORED AS TEXTFILE
		LOCATION 's3://pt-data-lab/raw-data/'
		TBLPROPERTIES ('skip.header.line.count'='1');
	QueryExecutionContext: {'Database': 'analytics', 'Catalog': 'AwsDataCatalog'}
	ResultConfiguration: {'OutputLocation': 's3://pt-data-lab/athena-staging/'}
	WorkGroup: primary
[2025-08-14T18:20:55.452+0000] {base_aws.py:587} WARNING - Unable to find AWS Connection ID 'aws_default', switching to empty.
[2025-08-14T18:20:55.453+0000] {base_aws.py:164} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2025-08-14T18:20:56.250+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-08-14T18:20:57.622+0000] {athena.py:135} INFO - Query execution id: f8c3ead4-4617-4307-bd1a-07b7e7985c6c
[2025-08-14T18:20:57.843+0000] {waiter_with_logging.py:78} INFO - Query execution id: f8c3ead4-4617-4307-bd1a-07b7e7985c6c, Query is still in non-terminal state: RUNNING
[2025-08-14T18:21:03.383+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-14T18:21:03.445+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=orders_pipeline, task_id=create_external_raw_orders, run_id=manual__2025-08-14T17:56:41+00:00, execution_date=20250814T175641, start_date=20250814T182054, end_date=20250814T182103
[2025-08-14T18:21:03.519+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-08-14T18:21:03.595+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-14T18:21:03.599+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
